#!/bin/bash

#$ -V                             # Inherit the submission environment
#$ -cwd                           # Start job in submission dir
#$ -N HAB6FDA                     # Job name
#$ -j y                           # Combine stderr and stdout into stdout
#$ -o $JOB_NAME-$JOB_ID.hst       # Name of the output file
#$ -pe 8way 64                    # 8 cores/node on Longhorn
#$ -q normal                      # Queue name
#$ -P gpgpu                       # project type
#$ -A PMD-GPU                     # Account
#$ -l h_rt=2:00:00                # runtime (hh:mm:ss) - 4 hours

ibrun -n 8 -o 0 \
    pmdgpu -box 32.1874 32.1874 32.1874 \
           -N 8 \
           -n 25 \
           -config_directory /home/00479/willmore/HAB-6FDA/gfg1/ \
           -config_prefix HAB_ \
           -config_suffix .gfg \
           -config_start 1 \
           -target_time 10.0 \
           -verlet_cutoff_sq 100.0 \
           -resolution_t 1.0 \
           -Helium \
           -T 308 \
           -use_mpi
