#!/bin/bash

# There were four unique sets of sigma/epsilon parameters identified for atoms in the atoms section.
# The PS100.atoms input file is generated by isolating the atoms section of the .lmps file.
# Running the script here will take the atoms records and transform them into gfg (x,y,z,sigma,epsilon) format.

CARBON_A="3.55\t0.07"
CARBON_B="3.5\t0.066"
HYDROGEN_C="2.5\t0.03"
HYDROGEN_D="2.42\t0.03"

while read -r -a array
do 
    atom_type=${array[2]}

    TYPE_CARBON_A=(1 2 3 4 5 6)
    TYPE_CARBON_B=(7 8 19 20)
    TYPE_HYDROGEN_C=(9 10 11 12 13)
    TYPE_HYDROGEN_D=(14 15 16 17 18)

    [[ " ${TYPE_CARBON_A[*]} " =~ " ${atom_type} " ]] && printf "${array[4]}\t${array[5]}\t${array[6]}\t${CARBON_A}\n"
    [[ " ${TYPE_CARBON_B[*]} " =~ " ${atom_type} " ]] && printf "${array[4]}\t${array[5]}\t${array[6]}\t${CARBON_B}\n"
    [[ " ${TYPE_HYDROGEN_C[*]} " =~ " ${atom_type} " ]] && printf "${array[4]}\t${array[5]}\t${array[6]}\t${HYDROGEN_C}\n"
    [[ " ${TYPE_HYDROGEN_D[*]} " =~ " ${atom_type} " ]] && printf "${array[4]}\t${array[5]}\t${array[6]}\t${HYDROGEN_D}\n"

done < PS100.atoms

